app:
  security:
    saml2:
      signing:
        private-key-location: "classpath:credentials/rp-private.key"
        certificate-location: "classpath:credentials/rp-certificate.crt"
      identityprovider:
        verification:
          key-store-location: "classpath:credentials/keystore.jks"
          key-store-password: "saml2sample"
          key-store-alias: "oktaCertificate"
        entity-id: http://www.okta.com/exkpxex5ilaUzCuyp0h7
        sso-url: https://schubergphilis.oktapreview.com/app/schubergphilis_springsecuritysample_1/exkpxex5ilaUzCuyp0h7/sso/saml
