spring:
  security:
    saml2:
      relyingparty:
        registration:
          simplesamlphp:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/rp-private.key"
                  certificate-location: "classpath:credentials/rp-certificate.crt"
            identityprovider:
              verification:
                credentials:
                  - certificate-location: "classpath:credentials/okta.cert"
              entity-id: http://www.okta.com/exkpxex5ilaUzCuyp0h7
              sso-url: https://schubergphilis.oktapreview.com/app/schubergphilis_springsecuritysample_1/exkpxex5ilaUzCuyp0h7/sso/saml
